language: node_js
node_js:
  - "9"
dist: trusty
sudo: true

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - yarn install

script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
