language: node_js
node_js:
  - "10"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn gh-pages
  - yarn install

script:
  - yarn build
  - gh-pages -d public -b master -r https://${GITHUB_TOKEN}@github.com/express-webpack-ultimate-guide/express-webpack-ultimate-guide.github.io.git
